apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: step
        image: chentex/random-logger
        args: ["100", "400", "100"]
      restartPolicy: Never
      nodeSelector:
        disktype: INVALID
  backoffLimit: 1
