apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: ubuntu:18.04
        command: ["sleep", "10000000"]
      restartPolicy: Never
  backoffLimit: 4
